version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    IMAGE_REPO_NAME: banking-system-backend

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building backend Docker image...
      - docker build -t $REPO_URI:latest Backend-Ledger
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Creating ECS image definition file...
      - printf '[{"name":"backend-container","imageUri":"%s"}]' "$REPO_URI:$IMAGE_TAG" > backend-imagedefinitions.json

artifacts:
  files:
    - backend-imagedefinitions.json